# Generated by Django 5.1.1 on 2024-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
