from .home import home
from .community import community
from .membership import membership
from .shop import shop
from .blogs import blogs
from .register import register
from .verify_email import verify_email
from .login import login
from .forgot_password import forgot_password
from .recover_password import recover_password
from .new_password import new_password