# Generated by Django 5.1.1 on 2024-10-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
